FROM python:3.12-alpine@sha256:78098ea6a3a9c6a7727a5d4674e4a44e57e01fac878ee9cb4d24a86bd93916ff
WORKDIR /app
COPY docker_broker.py /app/docker_broker.py
ENTRYPOINT ["python", "/app/docker_broker.py"]
